version: '3.3'

services:
  rabbitmq:
    image: rabbitmq:3.8.4-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_DEFAULT_VHOST: fsm
    ports:
      - "5672:5672"
      - "15672:15672"